# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(795, 606)
        font = QFont()
        font.setFamily(u"MS Sans Serif")
        MainWindow.setFont(font)
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionPor_ID = QAction(MainWindow)
        self.actionPor_ID.setObjectName(u"actionPor_ID")
        self.actionVelocidad = QAction(MainWindow)
        self.actionVelocidad.setObjectName(u"actionVelocidad")
        self.actionDistancia = QAction(MainWindow)
        self.actionDistancia.setObjectName(u"actionDistancia")
        self.actionGrafo = QAction(MainWindow)
        self.actionGrafo.setObjectName(u"actionGrafo")
        self.actionBusquedaGrafo = QAction(MainWindow)
        self.actionBusquedaGrafo.setObjectName(u"actionBusquedaGrafo")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 751, 500))
        self.ID = QSpinBox(self.groupBox)
        self.ID.setObjectName(u"ID")
        self.ID.setGeometry(QRect(40, 30, 141, 22))
        self.ID.setAccelerated(False)
        self.ID.setMaximum(10000000)
        self.Velocidad = QSpinBox(self.groupBox)
        self.Velocidad.setObjectName(u"Velocidad")
        self.Velocidad.setGeometry(QRect(240, 230, 111, 31))
        self.Velocidad.setMaximum(1000000)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 230, 151, 258))
        self.Verde = QScrollBar(self.groupBox_2)
        self.Verde.setObjectName(u"Verde")
        self.Verde.setGeometry(QRect(90, 20, 17, 191))
        self.Verde.setMaximum(255)
        self.Verde.setOrientation(Qt.Vertical)
        self.Azul = QScrollBar(self.groupBox_2)
        self.Azul.setObjectName(u"Azul")
        self.Azul.setGeometry(QRect(50, 20, 17, 191))
        self.Azul.setMaximum(255)
        self.Azul.setOrientation(Qt.Vertical)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 220, 31, 16))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 220, 41, 16))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 220, 31, 16))
        self.Rojo = QScrollBar(self.groupBox_2)
        self.Rojo.setObjectName(u"Rojo")
        self.Rojo.setGeometry(QRect(10, 23, 17, 191))
        self.Rojo.setMaximum(255)
        self.Rojo.setOrientation(Qt.Vertical)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 30, 47, 20))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 60, 361, 71))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 20, 20))
        self.OrigenX = QScrollBar(self.groupBox_3)
        self.OrigenX.setObjectName(u"OrigenX")
        self.OrigenX.setGeometry(QRect(30, 20, 321, 16))
        self.OrigenX.setMaximum(500)
        self.OrigenX.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 16, 16))
        self.OrigenY = QScrollBar(self.groupBox_3)
        self.OrigenY.setObjectName(u"OrigenY")
        self.OrigenY.setGeometry(QRect(30, 50, 321, 16))
        self.OrigenY.setMaximum(500)
        self.OrigenY.setOrientation(Qt.Horizontal)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 140, 361, 80))
        self.DestinoX = QScrollBar(self.groupBox_4)
        self.DestinoX.setObjectName(u"DestinoX")
        self.DestinoX.setGeometry(QRect(30, 30, 321, 16))
        self.DestinoX.setMaximum(500)
        self.DestinoX.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.groupBox_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 20, 20))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 20, 20))
        self.DestinoY = QScrollBar(self.groupBox_4)
        self.DestinoY.setObjectName(u"DestinoY")
        self.DestinoY.setGeometry(QRect(30, 60, 321, 16))
        self.DestinoY.setMaximum(500)
        self.DestinoY.setOrientation(Qt.Horizontal)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(170, 230, 71, 31))
        self.Mostrar = QPushButton(self.groupBox)
        self.Mostrar.setObjectName(u"Mostrar")
        self.Mostrar.setGeometry(QRect(200, 410, 151, 71))
        self.salida = QPlainTextEdit(self.groupBox)
        self.salida.setObjectName(u"salida")
        self.salida.setGeometry(QRect(383, 20, 361, 471))
        self.Iniciocap = QPushButton(self.groupBox)
        self.Iniciocap.setObjectName(u"Iniciocap")
        self.Iniciocap.setGeometry(QRect(200, 300, 151, 41))
        self.finalcap = QPushButton(self.groupBox)
        self.finalcap.setObjectName(u"finalcap")
        self.finalcap.setGeometry(QRect(200, 350, 151, 41))
        self.NumAct = QPlainTextEdit(self.groupBox)
        self.NumAct.setObjectName(u"NumAct")
        self.NumAct.setGeometry(QRect(200, 20, 171, 41))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout = QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Tabla = QTableWidget(self.tab_2)
        self.Tabla.setObjectName(u"Tabla")

        self.gridLayout.addWidget(self.Tabla, 0, 0, 1, 3)

        self.LineadeBusqueda = QLineEdit(self.tab_2)
        self.LineadeBusqueda.setObjectName(u"LineadeBusqueda")

        self.gridLayout.addWidget(self.LineadeBusqueda, 1, 0, 1, 1)

        self.Buscar_push = QPushButton(self.tab_2)
        self.Buscar_push.setObjectName(u"Buscar_push")

        self.gridLayout.addWidget(self.Buscar_push, 1, 1, 1, 1)

        self.Mostrartabla_push = QPushButton(self.tab_2)
        self.Mostrartabla_push.setObjectName(u"Mostrartabla_push")

        self.gridLayout.addWidget(self.Mostrartabla_push, 1, 2, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout_2 = QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.graphicsView = QGraphicsView(self.tab_3)
        self.graphicsView.setObjectName(u"graphicsView")

        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 2)

        self.Dibujarpush = QPushButton(self.tab_3)
        self.Dibujarpush.setObjectName(u"Dibujarpush")

        self.gridLayout_2.addWidget(self.Dibujarpush, 1, 0, 1, 1)

        self.Limpiarpush = QPushButton(self.tab_3)
        self.Limpiarpush.setObjectName(u"Limpiarpush")

        self.gridLayout_2.addWidget(self.Limpiarpush, 1, 1, 1, 1)

        self.tabWidget.addTab(self.tab_3, "")

        self.verticalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 795, 22))
        self.menuArchivos = QMenu(self.menubar)
        self.menuArchivos.setObjectName(u"menuArchivos")
        self.menuOrdenar_Particulas = QMenu(self.menubar)
        self.menuOrdenar_Particulas.setObjectName(u"menuOrdenar_Particulas")
        self.menuGrafo = QMenu(self.menubar)
        self.menuGrafo.setObjectName(u"menuGrafo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivos.menuAction())
        self.menubar.addAction(self.menuOrdenar_Particulas.menuAction())
        self.menubar.addAction(self.menuGrafo.menuAction())
        self.menuArchivos.addAction(self.actionAbrir)
        self.menuArchivos.addAction(self.actionGuardar)
        self.menuOrdenar_Particulas.addAction(self.actionPor_ID)
        self.menuOrdenar_Particulas.addAction(self.actionVelocidad)
        self.menuOrdenar_Particulas.addAction(self.actionDistancia)
        self.menuGrafo.addAction(self.actionGrafo)
        self.menuGrafo.addSeparator()
        self.menuGrafo.addAction(self.actionBusquedaGrafo)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Accion Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Accion Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPor_ID.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.actionVelocidad.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.actionDistancia.setText(QCoreApplication.translate("MainWindow", u"Distancia", None))
        self.actionGrafo.setText(QCoreApplication.translate("MainWindow", u"Transformar a Grafo", None))
#if QT_CONFIG(shortcut)
        self.actionGrafo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionBusquedaGrafo.setText(QCoreApplication.translate("MainWindow", u"Busqueda Profundidad/Amplitud", None))
#if QT_CONFIG(shortcut)
        self.actionBusquedaGrafo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Particula", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Color(RVA)", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Rojo", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Verde", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Azul", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Origen", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Destino", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.Mostrar.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.Iniciocap.setText(QCoreApplication.translate("MainWindow", u"Capturar Inicio", None))
        self.finalcap.setText(QCoreApplication.translate("MainWindow", u"Capturar Final", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.LineadeBusqueda.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID de la Particula", None))
        self.Buscar_push.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.Mostrartabla_push.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tabla", None))
        self.Dibujarpush.setText(QCoreApplication.translate("MainWindow", u"Dibujar", None))
        self.Limpiarpush.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Visor de Particulas", None))
        self.menuArchivos.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
        self.menuOrdenar_Particulas.setTitle(QCoreApplication.translate("MainWindow", u"Ordenar Particulas", None))
        self.menuGrafo.setTitle(QCoreApplication.translate("MainWindow", u"Grafo", None))
    # retranslateUi

